kdg

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,7 +1,19 @@
 #!/bin/sh
-export JAVA_HOME="/usr/lib/jvm/jdk-16" 
-export MAVEN_OPTS="-Xms1024m"
+export JAVA_HOME="/usr/lib/jvm/jdk-15.0.2"
+#export MAVEN_OPTS="-Xms1024m"
 rm -rf ../.m2/repository/org/dbs24
+mvn clean
 clear
 mvn -version
-mvn clean install validate
+
+mvn enforcer:enforce
+
+if [ $? -eq 0 ]
+then
+  mvn install verify -DskipTests=true
+else
+  RED='\033[0;31m'
+  echo -e "${RED}######### Could not build project #####################################################################"
+fi
+
+
